Repository cocos-pet/cocos-frontend, pull requests merged in 2025-06, with the labels that each got.

#304 [Feat/#304] 위치 바텀 시트
  src/api/constants/apiPath.ts
  src/api/domain/review/location/hook.ts
  src/api/domain/review/location/index.ts
  src/api/domain/review/types.ts
  src/app/review/_components/hospitalList/hospitalList.css.ts
  src/app/review/_components/hospitalList/hospitalList.tsx
  src/app/review/_components/hospitalList/mockData.ts
  src/app/review/_components/hospitalList/page.tsx
  src/app/review/_components/locationBottomSheet/CityTab.tsx
  src/app/review/_components/locationBottomSheet/locationBottomSheet.css.ts
  src/app/review/_components/locationBottomSheet/locationBottomSheet.tsx
  src/app/review/_components/locationHeader/locationHeader.css.ts
  src/app/review/_components/locationHeader/locationHeader.tsx
  src/app/review/_components/locationHeader/page.tsx
  src/app/review/locationHeader/locationHeader.tsx
  src/app/review/page.tsx
  src/app/review/style.css.ts
  src/asset/svg/IcCheck.tsx
  src/asset/svg/IcChevronDown.tsx
  src/asset/svg/index.ts
  src/type/schema.d.ts
Labels: 🎨 design, ✨ feat, 💄 style

#306 [Feat/#297] 부위별 병원 리뷰 api 연동, 리뷰 필터 요약 옵션 api 연동
  src/api/constants/apiPath.ts
  src/api/domain/community/detail/hook.ts
  src/api/domain/community/detail/index.ts
  src/app/community/_constant/reviewFilterConfig.ts
  src/app/community/_constant/reviewMockData.ts
  src/app/community/category/page.tsx
  src/app/community/detail/SymptomDetail.css.ts
  src/app/community/detail/_section/ReviewDetailContent.tsx
  src/app/community/detail/_section/ReviewFilter.tsx
  src/app/community/detail/page.tsx
  src/asset/svg/IcDownArrow.tsx
  src/common/component/Chip/Chip.tsx
  src/common/component/Chip/ChipStyle.css.ts
  src/shared/component/HospitalReview/HospitalReview.tsx
  src/shared/component/NoData/NoData.tsx
Labels: ✨ feat

#329 [Feat/#308] modal component 구현
  src/app/community/detail/page.tsx
  src/common/component/Modal/Modal.tsx
  src/common/component/Modal/context.ts
  src/common/component/Modal/group/ModalBottomAffix.tsx
  src/common/component/Modal/group/ModalClose.tsx
  src/common/component/Modal/group/ModalConfirm.tsx
  src/common/component/Modal/group/ModalContent.tsx
  src/common/component/Modal/group/ModalTitle.tsx
  src/common/component/Modal/style.css.ts
Labels: ✨ feat

#340 [Feat/#338] 비로그인 로직 작성(마이페이지, 프로필페이지 등등)
  src/app/profile/page.tsx
  src/app/setting/page.tsx
  src/shared/component/HospitalReviewWrapper.tsx
Labels: ✨ feat, 🍳 simple review

#348 [Bug][#347] 빌드테스트 실패 원인 해결
  src/app/setting/page.tsx
Labels: 🐞 fix

#355 hotfix: 비로그인시 search 화면 렌더링 안되는 문제 + 라우팅 버그 수정
  src/api/domain/community/search/hook.ts
  src/api/domain/hospitals/search/hook.ts
  src/app/community/search/Search.css.ts
  src/app/community/search/index/Search.tsx
  src/app/community/search/page.tsx
  src/app/main/page.tsx
  src/app/review/search/done/HospitalSearchDone.tsx
  src/app/review/search/hospitals/hospitals.tsx
  src/app/review/write/_component/DirectMyPetInfo.tsx
Labels: 🐞 fix

#356 [Feat] 타이머 시간 변하는 기능 추가
  src/app/not-found.tsx
Labels: ✨ feat, 🍳 simple review

#357 [Feat/#353] 가장 많이 찾는 병원 api 연동
  pnpm-lock.yaml
  src/api/domain/community/search/index.ts
  src/api/domain/main/hook.ts
  src/api/domain/main/index.ts
  src/api/shared/hook.ts
  src/api/shared/index.ts
  src/app/main/_component/HotHospitalItem/HotHospitalItem.tsx
  src/app/main/_section/hotHospital/HotHospital.tsx
  src/app/main/page.tsx
Labels: ✨ feat

#361 [Feat/#360] 병원메인-리뷰작성 비로그인 로직 추가
  src/app/review/page.tsx
  src/route/path.ts
Labels: ✨ feat

#388 [QA] [fix: 지도 이미지 안 뜨는 문제 해결]
  src/app/hospital-detail/[hospitalId]/_component/InfoContent/InfoContent.tsx
  src/app/hospital-detail/[hospitalId]/_component/KakaoMap/KakaoMap.tsx
  src/app/hospital-detail/[hospitalId]/_component/MapComponent/MapComponent.css.ts
  src/app/hospital-detail/[hospitalId]/_component/MapComponent/MapComponent.tsx
Labels: 🐞 fix

#386 [QA][#382] 마이페이지 / 프로필페이지 / 병원검색필터 QA 반영
  src/api/shared/hook.ts
  src/app/mypage/_component/AddFavoriteHospital.tsx
  src/app/mypage/_component/MyPageContent/MyPageContent.tsx
  src/app/mypage/_style/mypage.css.ts
  src/app/mypage/page.tsx
  src/app/onboarding/index/Onboarding.tsx
  src/app/profile/_component/ProfileSection/ProfileSection.tsx
  src/app/profile/_style/profile.css.ts
  src/app/profile/page.tsx
  src/auth/RedirectKakao.tsx
  src/common/component/Content/Content.tsx
  src/route/useProtectedRoute.tsx
  src/shared/component/HospitalReviewWrapper.tsx
  src/shared/component/SearchHospital/SearchHospital.tsx
Labels: 🐞 fix

#399 [QA][#398] 회원 탈퇴 페이지 반응형 구현
  src/app/setting/withdraw/page.css.ts
Labels: 🐞 fix, 🎨 design
