Repository cocos-pet/cocos-frontend, pull requests merged in 2025-01, with the labels that each got.

#4 [init] biome 초기세팅
  biome.json
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/page/community/post/Post.tsx
  src/page/community/search/Search.tsx
Labels: ⚙️ init

#10 [Feat/#8] API & Query 세팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/__generated__/schema.d.ts
  src/api/domain/main/hook.ts
  src/api/domain/main/index.ts
  src/api/index.ts
Labels: ⚙️ init

#14 [init] 오토 리뷰어 깃헙 액션 추가
  .github/auto_assign.yml
  .github/workflows/auto_assign.yml
Labels: ⚙️ init

#22 [Feat/#21] Spacing & Divider 컴포넌트 구현
  biome.json
  package.json
  pnpm-lock.yaml
  src/common/component/Divider/Divider.css.ts
  src/common/component/Divider/Divider.tsx
  src/common/component/Spacing/Spacing.css.ts
  src/common/component/Spacing/Spacing.tsx
  src/page/main/index/Main.tsx
Labels: 🐞 fix, ✨ feat, 💄 style

#19 [Feat] Button component
  README.md
  package.json
  pnpm-lock.yaml
  public/svgs/ic_test.svg
  src/asset/svg/IcTest.tsx
  src/asset/svg/index.ts
  src/common/component/Button/index.tsx
  src/common/component/Button/styles.css.ts
  src/common/component/TextField/index.tsx
  src/common/component/TextField/styles.css.ts
  src/page/main/index/Main.tsx
  src/style/global.css.ts
  src/style/reset.css.ts
Labels: ✨ feat, 💄 style

#29 [Feat]칩 공통컴포넌트 구현
  public/svgs/ic_delete.svg
  src/asset/svg/IcDelete.tsx
  src/asset/svg/index.ts
  src/common/component/Chip/Chip.tsx
  src/common/component/Chip/ChipStyle.css.ts
  src/page/main/index/Main.tsx
Labels: ✨ feat, 💄 style

#31 [Feat] Contents 컴포넌트 구현
  public/svgs/ico-message.svg
  public/svgs/ico-skeleton.svg
  src/asset/svg/IcoMessage.tsx
  src/asset/svg/IcoSkeleton.tsx
  src/asset/svg/index.ts
  src/common/component/Content/Content.css.ts
  src/common/component/Content/Content.tsx
Labels: ✨ feat, 💄 style

#24 [Feat] 플로팅 버튼 컴포넌트
  public/svgs/plus.svg
  src/asset/svg/Plus.tsx
  src/asset/svg/index.ts
  src/common/component/FloatingBtn/Floating.css.ts
  src/common/component/FloatingBtn/Floating.tsx
Labels: ✨ feat

#27 [Feat] 하단 Nav 컴포넌트 구현
  public/svgs/ic_Shape.svg
  src/asset/svg/IcShape.tsx
  src/asset/svg/index.ts
  src/common/component/Nav/Nav.css.ts
  src/common/component/Nav/Nav.tsx
  src/common/component/Nav/constant.ts
  src/page/main/index/Main.tsx
  src/page/mypage/index/Mypage.tsx
  src/style/reset.css.ts
Labels: ✨ feat, 💄 style

#32 [Feat/#26 ] 댓글 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  public/svgs/ic_Ellipse 57.svg
  public/svgs/ic_ellipses.svg
  public/svgs/ic_message.svg
  src/asset/svg/IcEllipse57.tsx
  src/asset/svg/IcEllipses.tsx
  src/asset/svg/IcMessage.tsx
  src/asset/svg/index.ts
  src/common/component/Comment/Comment.css.ts
  src/common/component/Comment/Comment.tsx
  src/page/main/index/Main.tsx
Labels: ✨ feat, 💄 style

#35 [ Feat/#33 ] 간단한 바텀시트 구현
  public/svgs/ic_BottomSheetLine.svg
  src/asset/svg/IcBottomSheetLine.tsx
  src/asset/svg/index.ts
  src/common/component/Button/styles.css.ts
  src/common/component/SimpleBottomSheet/SimpleBottomSheet.css.ts
  src/common/component/SimpleBottomSheet/SimpleBottomSheet.tsx
  src/page/main/index/Main.tsx
Labels: ✨ feat, 💄 style

#52 [Refactor/#51] 댓글 컴포넌트
  src/asset/svg/IcMessage.tsx
  src/common/component/Comment/Comment.css.ts
  src/common/component/Comment/Comment.tsx
  src/common/component/Comment/CommentList.tsx
  src/page/main/index/Main.tsx
  src/shared/constant/mockComment.ts
Labels: ♻️ refactor

#45 [Feat/#42] 검색 완료 뷰 구현
  public/svgs/ic_clear.svg
  public/svgs/ic_leftarrow.svg
  public/svgs/ic_search.svg
  public/svgs/ic_search_fillter.svg
  public/svgs/ic_search_fillter_blue.svg
  src/asset/svg/IcClear.tsx
  src/asset/svg/IcLeftarrow.tsx
  src/asset/svg/IcSearch.tsx
  src/asset/svg/IcSearchFillter.tsx
  src/asset/svg/IcSearchFillterBlue.tsx
  src/asset/svg/index.ts
  src/common/component/Content/Content.css.ts
  src/common/component/TextField/index.tsx
  src/common/component/TextField/styles.css.ts
  src/page/community/[postId]/Post.tsx
  src/page/community/post/Post.tsx
  src/page/community/search/Search.tsx
  src/page/community/search/done/SearchDone.css.ts
  src/page/community/search/done/SearchDone.tsx
  src/page/community/search/index/Search.css.ts
  src/page/community/search/index/Search.tsx
  src/route/Community.tsx
  src/route/path.ts
  src/shared/constant/recentSearchData.ts
  src/shared/constant/searchDoneData.ts
Labels: ✨ feat

#34 [Feat/#23] Tab & TextBox & BottomSheet & FilterBottomSheet
  biome.json
  public/svgs/check.svg
  public/svgs/ic_up.svg
  src/asset/svg/Check.tsx
  src/asset/svg/IcUp.tsx
  src/asset/svg/index.ts
  src/common/component/BottomSheet/BottomSheet.css.ts
  src/common/component/BottomSheet/BottomSheet.tsx
  src/common/component/Button/index.tsx
  src/common/component/Button/styles.css.ts
  src/common/component/CheckBoxText/CheckBoxText.css.ts
  src/common/component/CheckBoxText/CheckBoxText.tsx
  src/common/component/Chip/Chip.tsx
  src/common/component/Chip/ChipStyle.css.ts
  src/common/component/DropDownText/DropDownText.css.ts
  src/common/component/DropDownText/DropDownText.tsx
  src/common/component/Tab/Tab.css.ts
  src/common/component/Tab/Tab.tsx
  src/index.css
  src/main.tsx
  src/page/main/index/Main.tsx
  src/page/mypage/index/Mypage.tsx
  src/shared/component/FilterBottomSheet/CategoryContent/CategoryContent.css.ts
  src/shared/component/FilterBottomSheet/CategoryContent/CategoryContent.tsx
  src/shared/component/FilterBottomSheet/CategoryContent/constant.ts
  src/shared/component/FilterBottomSheet/FilterBottomSheet.css.ts
  src/shared/component/FilterBottomSheet/FilterBottomSheet.tsx
  src/store/filter.ts
  src/style/styles.css.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🐞 fix, 🎨 design, ✨ feat, ♻️ refactor

#64 [Feat/#60] 게시물 삭제 모달 구현
  src/common/component/BottomSheet/BottomSheet.tsx
  src/page/community/[postId]/Post.ts
  src/page/community/[postId]/Post.tsx
  src/shared/component/MoreModal/MoreModal.css.ts
  src/shared/component/MoreModal/MoreModal.tsx
  src/shared/constant/.gitkeep
  src/shared/hook/.gitkeep
  src/shared/hook/useMoreModal.ts
Labels: ✨ feat, 💄 style

#66 [Feat/#61] 양자택일 컴포넌트 구현
  src/asset/image/image 1733.png
  src/page/onboarding/index/Onboarding.tsx
  src/page/onboarding/index/component/dualOptionSelector/DualOptionSelector.css.ts
  src/page/onboarding/index/component/dualOptionSelector/DualOptionSelector.tsx
Labels: ✨ feat

#81 [Feat/#78] 프로필 페이지 구현 (타인이 봤을 때 마이페이지)
  public/svgs/ic_chevron-left.svg
  public/svgs/ic_chevron-right.svg
  public/svgs/ic_plus.svg
  public/svgs/ic_settings.svg
  src/asset/svg/IcChevronLeft.tsx
  src/asset/svg/IcChevronRight.tsx
  src/asset/svg/IcPlus.tsx
  src/asset/svg/IcSettings.tsx
  src/asset/svg/index.ts
  src/common/component/Nav/Nav.css.ts
  src/common/component/Nav/Nav.tsx
  src/common/component/Tab/Tab.tsx
  src/page/main/index/Main.tsx
  src/page/mypage/index/ constant.ts
  src/page/mypage/index/Mypage.css.ts
  src/page/mypage/index/Mypage.tsx
  src/page/mypage/index/component/MyPageComment/MyPageComment.css.ts
  src/page/mypage/index/component/MyPageComment/MyPageComment.tsx
  src/page/mypage/index/component/MyPageContent/MyPageContent.css.ts
  src/page/mypage/index/component/MyPageContent/MyPageContent.tsx
  src/page/mypage/index/component/MyPageContent/costant.ts
  src/page/profile/index/ constant.ts
  src/page/profile/index/Profile.css.ts
  src/page/profile/index/Profile.tsx
  src/page/profile/index/component/ProfileComment/ProfileComment.css.ts
  src/page/profile/index/component/ProfileComment/ProfileComment.tsx
  src/page/profile/index/component/ProfileContent/ProfileContent.css.ts
  src/page/profile/index/component/ProfileContent/ProfileContent.tsx
  src/page/profile/index/component/ProfileContent/costant.ts
  src/route/ProfileRoutes.tsx
  src/route/Router.tsx
  src/route/index.ts
  src/route/path.ts
  src/shared/util/renderAllComents.ts
Labels: 🎨 design, ✨ feat, 🛠️ rename

#91 [Refactor/#90] SimpleBottomSheet 리팩토링
  src/common/component/SimpleBottomSheet/SimpleBottomSheet.css.ts
  src/common/component/SimpleBottomSheet/SimpleBottomSheet.tsx
  src/page/test/Test.tsx
  src/route/Router.tsx
  src/shared/hook/useSimpleBottomSheet.ts
Labels: 💄 style, ♻️ refactor

#77 [feat/#74] textArea 컴포넌트로 구현
  src/page/community/component/TextArea/TextArea.css.ts
  src/page/community/component/TextArea/TextArea.tsx
  src/page/community/write/Write.tsx
Labels: ✨ feat, 💄 style

#87 [feat/#76] Tag 컴포넌트
  public/svgs/ic_right.svg
  src/asset/svg/IcRight.tsx
  src/asset/svg/index.ts
  src/page/community/component/Tag/Tag.css.ts
  src/page/community/component/Tag/Tag.tsx
  src/page/community/write/Write.tsx
Labels: ✨ feat, 💄 style

#68 [Feat/#67] 펫 이름 뷰 구현
  src/page/onboarding/index/Onboarding.tsx
  src/page/onboarding/index/component/petName/PetName.css.ts
  src/page/onboarding/index/component/petName/PetName.tsx
  src/page/onboarding/index/constant/errorMsg.ts
  src/page/onboarding/index/util/validateNickname.ts
  src/page/onboarding/index/util/validatePetName.ts
Labels: 🎨 design, ✨ feat

#72 [Feat/#49] 게시물 detail 페이지 구현
  public/svgs/ic_postImage_skeleton.svg
  src/asset/svg/IcBottomSheetLine.tsx
  src/asset/svg/IcClear.tsx
  src/asset/svg/IcEllipse57.tsx
  src/asset/svg/IcEllipses.tsx
  src/asset/svg/IcLeftarrow.tsx
  src/asset/svg/IcMessage.tsx
  src/asset/svg/IcPostImageSkeleton.tsx
  src/asset/svg/IcSearch.tsx
  src/asset/svg/IcSearchFillter.tsx
  src/asset/svg/IcSearchFillterBlue.tsx
  src/asset/svg/IcTest.tsx
  src/asset/svg/IcoMessage.tsx
  src/asset/svg/IcoSkeleton.tsx
  src/asset/svg/index.ts
  src/common/component/Button/styles.css.ts
  src/common/component/Chip/Chip.tsx
  src/common/component/Comment/Comment.css.ts
  src/common/component/Comment/Comment.tsx
  src/common/component/Comment/CommentList.tsx
  src/common/component/Content/Content.tsx
  src/common/component/HeaderNav/HeaderNav.css.ts
  src/common/component/HeaderNav/HeaderNav.tsx
  src/common/component/Spacing/Spacing.css.ts
  src/common/component/SubComment/SubComment.css.ts
  src/common/component/SubComment/SubComment.tsx
  src/common/component/TextField/styles.css.ts
  src/page/community/[postId]/Post.css.ts
  src/page/community/[postId]/Post.tsx
  src/page/community/search/done/SearchDone.css.ts
  src/page/community/search/done/SearchDone.tsx
  src/page/community/search/index/Search.css.ts
  src/shared/component/MoreModal/MoreModal.tsx
  src/shared/util/formatTime.ts
  src/store/moreModalStore.ts
  src/style/styles.css.ts
Labels: ✨ feat, 💄 style

#70 [Feat/#69]펫 나이 뷰 구현
  src/common/component/TextField/index.tsx
  src/common/component/TextField/styles.css.ts
  src/page/onboarding/index/component/nickname/Nickname.tsx
  src/page/onboarding/index/component/petAge/PetAge.css.ts
  src/page/onboarding/index/component/petAge/PetAge.tsx
Labels: 🎨 design, 💄 style

#79 [Feat/#71] 반려동물 질병 유무 뷰 구현
  src/common/component/Button/styles.css.ts
  src/page/onboarding/index/Onboarding.tsx
  src/page/onboarding/index/component/petHealth/PetHealth.tsx
  src/page/onboarding/index/component/petHealth/disease/Disease.tsx
  src/page/onboarding/index/component/petHealth/petHealthDualSelector/PetHealthDualSelector.css.ts
  src/page/onboarding/index/component/petHealth/petHealthDualSelector/PetHealthDualSelector.tsx
  src/page/onboarding/index/component/petHealth/symptom/Symptom.tsx
Labels: 🎨 design, ✨ feat

#95 [Feat/#83] 프로필 수정 페이지 구현
  public/svgs/ic_edit_pen.svg
  public/svgs/ic_out.svg
  src/asset/svg/IcEditPen.tsx
  src/asset/svg/IcOut.tsx
  src/asset/svg/index.ts
  src/page/mypage/edit-pet/PetEdit.tsx
  src/page/mypage/index/Mypage.tsx
  src/page/mypage/modify/Modify.tsx
  src/page/setting/edit-profile/ProfileEdit.css.ts
  src/page/setting/edit-profile/ProfileEdit.tsx
  src/page/setting/index/Setting.css.ts
  src/page/setting/index/Setting.tsx
  src/route/MyPageRoutes.tsx
  src/route/Router.tsx
  src/route/Setting.tsx
  src/route/index.ts
  src/route/path.ts
Labels: 🎨 design, ✨ feat

#88 [Feat/#85] 반려동물 대분류 뷰 구현
  src/asset/svg/index.ts
  src/common/component/HeaderNav/HeaderNav.css.ts
  src/page/onboarding/index/Onboarding.tsx
  src/page/onboarding/index/component/dualOptionSelector/DualOptionSelector.css.ts
  src/page/onboarding/index/component/dualOptionSelector/DualOptionSelector.tsx
  src/page/onboarding/index/component/petType/PetType.css.ts
  src/page/onboarding/index/component/petType/PetType.tsx
Labels: 🎨 design, ✨ feat

#92 [Feat/#89] 반려동물 성별 뷰
  src/page/onboarding/index/component/petGender/PetGender.css.ts
  src/page/onboarding/index/component/petGender/PetGender.tsx
  src/page/onboarding/index/constant/genderData.ts
Labels: 🎨 design, ✨ feat

#102 [Feat/#73] 게시물 작성 페이지 구현
  public/svgs/ic_ImagePlus.svg
  public/svgs/ic_delete_black.svg
  public/svgs/ic_delete_white.svg
  public/svgs/ic_rightArror.svg
  src/asset/svg/IcDeleteBlack.tsx
  src/asset/svg/IcDeleteWhite.tsx
  src/asset/svg/IcImagePlus.tsx
  src/asset/svg/IcRightArror.tsx
  src/asset/svg/index.ts
  src/common/component/BottomSheet/BottomSheet.css.ts
  src/common/component/CheckBoxText/CheckBoxText.tsx
  src/common/component/Chip/Chip.tsx
  src/common/component/HeaderNav/HeaderNav.css.ts
  src/common/component/TextField/index.tsx
  src/common/component/TextField/styles.css.ts
  src/page/community/component/DropDown/DropDown.css.ts
  src/page/community/component/DropDown/DropDown.tsx
  src/page/community/component/ImageCover/ImageCover.css.ts
  src/page/community/component/ImageCover/ImageCover.tsx
  src/page/community/component/Tag/Tag.tsx
  src/page/community/component/TextArea/TextArea.css.ts
  src/page/community/component/TextArea/TextArea.tsx
  src/page/community/component/WriteInputSection/WriteInputSection.css.ts
  src/page/community/component/WriteInputSection/WriteInputSection.tsx
  src/page/community/write/Write.css.ts
  src/page/community/write/Write.tsx
  src/shared/component/FilterBottomSheet/CategoryContent/CategoryContent.css.ts
  src/shared/component/FilterBottomSheet/FilterBottomSheet.css.ts
  src/shared/util/checkKeysInParams.ts
  src/store/filter.ts
Labels: 🎨 design, ✨ feat

#108 [Feat/#100] 뷰 변경사항 반영
  src/page/onboarding/index/constant/onboardingGuide.ts
  src/page/onboarding/index/util/validatePetName.ts
  src/page/registerPet/index/common/dualOptionSelector/DualOptionSelector.css.ts
  src/page/registerPet/index/common/dualOptionSelector/DualOptionSelector.tsx
  src/page/registerPet/index/component/petAge/PetAge.css.ts
  src/page/registerPet/index/component/petAge/PetAge.tsx
  src/page/registerPet/index/component/petGender/PetGender.css.ts
  src/page/registerPet/index/component/petGender/PetGender.tsx
  src/page/registerPet/index/component/petHealth/PetHealth.tsx
  src/page/registerPet/index/component/petHealth/disease/Disease.tsx
  src/page/registerPet/index/component/petHealth/petHealthDualSelector/PetHealthDualSelector.css.ts
  src/page/registerPet/index/component/petHealth/petHealthDualSelector/PetHealthDualSelector.tsx
  src/page/registerPet/index/component/petHealth/symptom/Symptom.tsx
  src/page/registerPet/index/component/petId/PetId.css.ts
  src/page/registerPet/index/component/petId/PetId.tsx
  src/page/registerPet/index/component/petName/PetName.css.ts
  src/page/registerPet/index/component/petName/PetName.tsx
  src/page/registerPet/index/component/petType/PetType.css.ts
  src/page/registerPet/index/component/petType/PetType.tsx
  src/page/registerPet/index/constant/genderData.ts
  src/route/RegisterPetRoutes.tsx
Labels: 🎨 design, ✨ feat

#63 [Feat/#41] 메인 뷰 구현
  package.json
  pnpm-lock.yaml
  public/svgs/ic_temporary.svg
  src/asset/image/_carousel_ex.png
  src/asset/image/_carousel_ex2.png
  src/asset/image/_carousel_ex3.png
  src/asset/image/skin.png
  src/asset/svg/IcClear.tsx
  src/asset/svg/IcTemporary.tsx
  src/asset/svg/index.ts
  src/common/component/Nav/Nav.css.ts
  src/common/component/TextField/styles.css.ts
  src/page/main/index/Main.css.ts
  src/page/main/index/Main.tsx
  src/page/main/index/hotPost/HotPost.css.ts
  src/page/main/index/hotPost/HotPost.tsx
  src/page/main/index/mainFooter/MainFooter.css.ts
  src/page/main/index/mainFooter/MainFooter.tsx
  src/page/main/index/mainHeader/Carousel/Images.ts
  src/page/main/index/mainHeader/Carousel/mainCarousel.css.ts
  src/page/main/index/mainHeader/Carousel/mainCarousel.tsx
  src/page/main/index/mainHeader/mainHeader.css.ts
  src/page/main/index/mainHeader/mainHeader.tsx
  src/page/main/index/symptom/Symptom.css.ts
  src/page/main/index/symptom/Symptom.tsx
  src/page/mypage/index/Mypage.tsx
  src/shared/constant/symptomMock.ts
Labels: ✨ feat, 💄 style

#101 [Feat/#94] 이미지 첨부된 완료 뷰 구현
  src/asset/image/beforeRegisterGraphic.png
  src/asset/svg/index.ts
  src/page/community/component/Tag/Tag.tsx
  src/page/onboarding/complete/Complete.css.ts
  src/page/onboarding/complete/Complete.tsx
  src/page/registerPet/complete/Complete.css.ts
  src/page/registerPet/complete/Complete.tsx
Labels: 🎨 design, ✨ feat

#113 [Feat/#109] 질병/증상 뷰 구현 ~플로우 연결
  public/svgs/ic_Icons.svg
  src/asset/svg/IcIcons.tsx
  src/asset/svg/index.ts
  src/common/component/Chip/Chip.tsx
  src/page/registerPet/index/RegisterPet.tsx
  src/page/registerPet/index/common/dropDown/DropDown.css.ts
  src/page/registerPet/index/common/dropDown/DropDown.tsx
  src/page/registerPet/index/common/dropDown/constant.ts
  src/page/registerPet/index/component/petAge/PetAge.tsx
  src/page/registerPet/index/component/petGender/PetGender.tsx
  src/page/registerPet/index/component/petHealth/PetHealth.tsx
  src/page/registerPet/index/component/petHealth/disease/Step1.css.ts
  src/page/registerPet/index/component/petHealth/disease/Step1.tsx
  src/page/registerPet/index/component/petHealth/disease/constant.ts
  src/page/registerPet/index/component/petHealth/petHealthDualSelector/PetHealthDualSelector.css.ts
  src/page/registerPet/index/component/petHealth/symptom/Step2.css.ts
  src/page/registerPet/index/component/petHealth/symptom/Step2.tsx
  src/page/registerPet/index/component/petHealth/symptom/constant.ts
  src/page/registerPet/index/component/petId/PetId.tsx
  src/page/registerPet/index/component/petName/PetName.tsx
  src/page/registerPet/index/component/petType/PetType.tsx
Labels: 🎨 design, ✨ feat

#121 [Feat/#103] 게시물 상세 페이지 api 연동
  src/api/domain/community/post/hook.ts
  src/api/domain/community/post/index.ts
  src/api/domain/community/search/hook.ts
  src/common/component/HeaderNav/HeaderNav.css.ts
  src/common/component/SubComment/SubComment.tsx
  src/page/community/[postId]/Post.css.ts
  src/page/community/[postId]/Post.tsx
  src/shared/util/formatTime.ts
  src/store/moreModalStore.ts
Labels: 🚀api

#124 [Feat/#110] 최근 검색어 post api 연동
  src/App.tsx
  src/api/domain/community/search/hook.ts
  src/api/domain/community/search/index.ts
  src/page/community/[postId]/Post.tsx
  src/page/community/search/index/Search.css.ts
  src/page/community/search/index/Search.tsx
  src/type/schema.d.ts
Labels: ✨ feat, 🚀api

#126 [Feat/#125] 검색 결과 api 연동
  src/api/constants/apiPath.ts
  src/api/domain/community/search/hook.ts
  src/api/domain/community/search/index.ts
  src/common/component/Content/Content.tsx
  src/page/community/search/done/SearchDone.tsx
  src/page/mypage/index/component/MyPageContent/MyPageContent.tsx
  src/page/profile/index/component/ProfileContent/ProfileContent.tsx
Labels: 🚀api

#128 [Feat/#127] 좋아요 추가, 삭제 api 연동
  public/svgs/ic_like_active.svg
  public/svgs/ic_like_disabled.svg
  src/api/domain/community/post/hook.ts
  src/api/domain/community/post/index.ts
  src/api/domain/community/search/hook.ts
  src/api/domain/community/search/index.ts
  src/api/index.ts
  src/asset/svg/IcLikeActive.tsx
  src/asset/svg/IcLikeDisabled.tsx
  src/asset/svg/index.ts
  src/page/community/[postId]/Post.tsx
  src/page/community/component/Tag/Tag.tsx
  src/type/schema.d.ts
Labels: 🚀api

#133 [Feat/#130/post] 댓글 & 대댓글 api 연동
  package.json
  pnpm-lock.yaml
  src/api/domain/community/post/hook.ts
  src/api/domain/community/post/index.ts
  src/api/domain/community/search/hook.ts
  src/api/domain/community/search/index.ts
  src/common/component/Comment/Comment.tsx
  src/common/component/Comment/CommentList.tsx
  src/common/component/SubComment/SubComment.tsx
  src/common/component/SubComment/SubCommentList.tsx
  src/page/community/[postId]/Post.tsx
  src/store/moreModalStore.ts
Labels: 🚀api

#107 [Feat/#65] 커뮤니티 뷰/ 대분류 구현
  public/svgs/Icfilteron.svg
  public/svgs/ic_cocos.svg
  public/svgs/ic_underline.svg
  public/svgs/icfilter.svg
  src/asset/image/image_banner.png
  src/asset/svg/IcCocos.tsx
  src/asset/svg/IcUnderline.tsx
  src/asset/svg/Icfilter.tsx
  src/asset/svg/Icfilteron.tsx
  src/asset/svg/index.ts
  src/common/component/Content/Content.css.ts
  src/common/component/Content/Content.tsx
  src/common/component/FloatingBtn/Floating.tsx
  src/common/component/Nav/Nav.css.ts
  src/common/component/Nav/Nav.tsx
  src/common/component/Nav/communityConstant.ts
  src/common/component/TextField/index.tsx
  src/page/community/category/Category.css.ts
  src/page/community/category/Category.tsx
  src/page/community/index/Community.css.ts
  src/page/community/index/Community.tsx
  src/page/community/index/components/Banner/Banner.css.ts
  src/page/community/index/components/Banner/Banner.tsx
  src/page/community/index/components/SelectPost/SelectPost.css.ts
  src/page/community/index/components/SelectPost/SelectPost.tsx
  src/page/community/search/done/SearchDone.tsx
  src/page/main/index/Main.css.ts
  src/page/main/index/Main.tsx
  src/page/mypage/index/Mypage.tsx
  src/page/profile/index/Profile.tsx
  src/route/Community.tsx
  src/route/path.ts
  src/shared/constant/postData.ts
Labels: 🎨 design, ✨ feat, ♻️ refactor

#134 [Feat/#131] 품종 조회 api 연동
  src/api/domain/registerPet/petId/hook.ts
  src/api/domain/registerPet/petId/index.ts
  src/page/registerPet/index/RegisterPet.tsx
  src/page/registerPet/index/common/dropDown/constant.ts
  src/page/registerPet/index/component/petId/PetId.tsx
Labels: ✨ feat, 🚀api

#129 [Feat/#122] 메인 뷰 API 연결 !
  src/api/domain/main/hook.ts
  src/api/domain/main/index.ts
  src/page/community/index/Community.tsx
  src/page/main/index/Main.tsx
  src/page/main/index/hotPost/HotPost.tsx
  src/page/main/index/symptom/Symptom.tsx
  src/shared/constant/symptomMock.ts
  src/store/filter.ts
  src/type/schema.d.ts
Labels: ✨ feat, 🚀api

#141 [Feat/#137] 질병, 증상 신체 1차 선택에 따른 2차 선택 api 연동
  src/api/domain/registerPet/disease/hook.ts
  src/api/domain/registerPet/disease/index.ts
  src/api/domain/registerPet/symptom/hook.ts
  src/api/domain/registerPet/symptom/index.ts
  src/page/registerPet/index/component/petHealth/PetHealth.tsx
  src/page/registerPet/index/component/petHealth/disease/Step1.css.ts
  src/page/registerPet/index/component/petHealth/disease/Step1.tsx
  src/page/registerPet/index/component/petHealth/disease/Step2.tsx
  src/page/registerPet/index/component/petHealth/disease/Step2Constant.ts
  src/page/registerPet/index/component/petHealth/symptom/SymStep1.tsx
  src/page/registerPet/index/component/petHealth/symptom/SymStep2.tsx
  src/page/registerPet/index/component/petHealth/symptom/SymStep2Constant.ts
Labels: 🎨 design, 🚀api

#143 [Feat/#136] 마이페이지 & 프로필페이지 API 연결
  src/api/domain/mypage/edit-pet/hook.ts
  src/api/domain/mypage/edit-pet/index.ts
  src/api/domain/mypage/hook.ts
  src/api/domain/mypage/index.ts
  src/api/index.ts
  src/page/mypage/edit-pet/PetEdit.css.ts
  src/page/mypage/edit-pet/PetEdit.tsx
  src/page/mypage/index/Mypage.tsx
  src/page/mypage/index/component/MyPageComment/MyPageComment.tsx
  src/page/mypage/index/component/MyPageContent/MyPageContent.css.ts
  src/page/mypage/index/component/MyPageContent/MyPageContent.tsx
  src/page/profile/index/Profile.css.ts
  src/page/profile/index/Profile.tsx
  src/page/profile/index/component/ProfileComment/ProfileComment.css.ts
  src/page/profile/index/component/ProfileComment/ProfileComment.tsx
  src/page/profile/index/component/ProfileContent/ProfileContent.css.ts
  src/page/profile/index/component/ProfileContent/ProfileContent.tsx
  src/page/setting/edit-profile/ProfileEdit.css.ts
  src/page/setting/edit-profile/ProfileEdit.tsx
  src/page/setting/index/Setting.css.ts
  src/shared/util/renderAllComents.ts
  src/type/schema.d.ts
Labels: 🐞 fix, 🎨 design, 🚀api

#144 [Feat/#142] 닉네임 조회 api
  src/api/domain/complete/hook.ts
  src/api/domain/complete/index.ts
  src/page/onboarding/complete/Complete.tsx
  src/page/registerPet/complete/Complete.tsx
Labels: 🚀api

#148 [Feat/#145] 닉네임 중복검사 api 연동
  src/api/domain/onboarding/nicknameDuplicate/hook.ts
  src/api/domain/onboarding/nicknameDuplicate/index.ts
  src/page/onboarding/index/component/nickname/Nickname.tsx
  src/shared/util/validateNickname.ts
Labels: ✨ feat, 🚀api

#157 [Feat/#138] 카테고리 대분류 API 연동/ 하단 Nav 바 아이콘 추가/ 최신글/ 인기글 리스트 API 연동
  public/svgs/ic_community.svg
  public/svgs/ic_communityon.svg
  public/svgs/ic_home.svg
  public/svgs/ic_homeon.svg
  public/svgs/ic_mypage.svg
  public/svgs/ic_mypageon.svg
  public/svgs/ic_review.svg
  public/svgs/ic_reviewoff.svg
  public/svgs/ic_reviewon.svg
  src/api/domain/community/category/hook.ts
  src/api/domain/community/category/index.ts
  src/asset/image/banner.png
  src/asset/svg/IcCommunity.tsx
  src/asset/svg/IcCommunityon.tsx
  src/asset/svg/IcHome.tsx
  src/asset/svg/IcHomeon.tsx
  src/asset/svg/IcMypage.tsx
  src/asset/svg/IcMypageon.tsx
  src/asset/svg/IcReviewoff.tsx
  src/asset/svg/IcReviewon.tsx
  src/asset/svg/index.ts
  src/common/component/Nav/Nav.css.ts
  src/common/component/Nav/Nav.tsx
  src/common/component/Nav/constant.ts
  src/page/community/category/Category.tsx
  src/page/community/index/Community.css.ts
  src/page/community/index/Community.tsx
  src/page/community/index/components/Banner/Banner.tsx
  src/page/community/index/components/SelectPost/SelectPost.tsx
Labels: ✨ feat, 🚀api

#160 [Feat/#158] 온보딩 ~ 반려동물 등록 반응형 레이아웃 구현 및 데이터 요청 시 깜빡임 문제 해결
  src/api/domain/register-pet/petId/hook.ts
  src/page/onboarding/index/component/nickname/Nickname.tsx
  src/page/register-pet/index/common/ProgressBar/ProgressBar.css.ts
  src/page/register-pet/index/component/petHealth/disease/Step1.css.ts
  src/page/register-pet/index/component/petHealth/disease/Step1.tsx
  src/page/register-pet/index/component/petHealth/disease/Step2.css.ts
  src/page/register-pet/index/component/petHealth/symptom/SymStep1.tsx
  src/page/register-pet/index/component/petId/PetId.tsx
  src/page/register-pet/index/component/petName/PetName.css.ts
  src/page/register-pet/index/component/petName/PetName.tsx
Labels: 🐞 fix, 🎨 design

#171 [Feat/#161] 닉네임 요청 api 연동
  src/api/domain/onboarding/nickname/hook.ts
  src/api/domain/onboarding/nickname/index.ts
  src/api/domain/register-pet/disease/hook.ts
  src/api/domain/register-pet/disease/index.ts
  src/api/domain/register-pet/symptom/hook.ts
  src/api/domain/register-pet/symptom/index.ts
  src/page/onboarding/index/Onboarding.tsx
  src/page/onboarding/index/component/nickname/Nickname.tsx
  src/page/register-pet/index/component/petHealth/PetHealth.tsx
  src/page/register-pet/index/component/petHealth/disease/Step2.tsx
  src/page/register-pet/index/component/petHealth/symptom/SymStep2.tsx
Labels: ✨ feat, 🚀api

#166 [Feat/#153] 게시물 작성 api, 이미지 api 연동 (with. 질병, 증상 api 연동)
  public/svgs/ic_baseProfileImage.svg
  public/svgs/ic_cocosM.svg
  public/svgs/ic_curious.svg
  public/svgs/ic_healing.svg
  public/svgs/ic_hospital.svg
  public/svgs/ic_symptom.svg
  src/api/domain/community/post/hook.ts
  src/api/domain/community/write/hook.ts
  src/api/domain/community/write/index.ts
  src/asset/svg/IcBaseProfileImage.tsx
  src/asset/svg/IcCocosM.tsx
  src/asset/svg/IcCurious.tsx
  src/asset/svg/IcHealing.tsx
  src/asset/svg/IcHospital.tsx
  src/asset/svg/IcReview.tsx
  src/asset/svg/IcSymptom.tsx
  src/asset/svg/index.ts
  src/common/component/Content/Content.css.ts
  src/common/component/Content/Content.tsx
  src/common/component/Nav/constant.ts
  src/common/component/TextField/index.tsx
  src/common/component/TextField/styles.css.ts
  src/page/community/[postId]/PostDetail.tsx
  src/page/community/component/DropDown/DropDown.tsx
  src/page/community/component/Tag/Tag.css.ts
  src/page/community/component/Tag/Tag.tsx
  src/page/community/constant/writeConfig.tsx
  src/page/community/index/components/SelectPost/SelectPost.tsx
  src/page/community/search/done/SearchDone.css.ts
  src/page/community/search/done/SearchDone.tsx
  src/page/community/search/index/Search.tsx
  src/page/community/utills/getFillterNamebyid.ts
  src/page/community/utills/handleCategoryItem.tsx
  src/page/community/write/Write.tsx
  src/page/mypage/edit-pet/PetEdit.tsx
  src/page/mypage/edit-pet/store/animalFilter.ts
  src/shared/component/FilterBottomSheet/CategoryContent/CategoryContent.tsx
  src/shared/component/FilterBottomSheet/CategoryContent/constant.ts
  src/shared/component/FilterBottomSheet/FilterBottomSheet.tsx
  src/shared/util/getSelectedChipNamesById.ts
  src/store/filter.ts
  src/style/global.css.ts
Labels: ✨ feat, 🚀api

#185 [Feat/#181] 온보딩 QA 반영
  public/svgs/ic-Group.svg
  public/svgs/ic-cocosLogin.svg
  src/asset/svg/IcCocosLogin.tsx
  src/asset/svg/IcGroup.tsx
  src/asset/svg/index.ts
  src/page/login/Login.css.ts
  src/page/login/Login.tsx
  src/page/onboarding/index/component/nickname/Nickname.tsx
  src/page/register-pet/complete/Complete.tsx
  src/page/register-pet/index/common/dualOptionSelector/DualOptionSelector.css.ts
  src/page/register-pet/index/component/petAge/PetAge.css.ts
  src/page/register-pet/index/component/petAge/PetAge.tsx
  src/page/register-pet/index/component/petGender/PetGender.css.ts
  src/page/register-pet/index/component/petGender/PetGender.tsx
  src/page/register-pet/index/component/petHealth/PetHealth.tsx
  src/page/register-pet/index/component/petHealth/disease/Step1.css.ts
  src/page/register-pet/index/component/petHealth/disease/Step1.tsx
  src/page/register-pet/index/component/petHealth/disease/Step2Constant.ts
  src/page/register-pet/index/component/petHealth/petHealthDualSelector/PetHealthDualSelector.css.ts
  src/page/register-pet/index/component/petHealth/petHealthDualSelector/PetHealthDualSelector.tsx
  src/page/register-pet/index/component/petHealth/symptom/SymStep1.tsx
  src/page/register-pet/index/component/petName/PetName.css.ts
  src/page/register-pet/index/component/petName/PetName.tsx
  src/page/register-pet/index/component/petType/PetType.css.ts
  src/page/register-pet/index/component/petType/PetType.tsx
  src/shared/constant/errorMsg.ts
  src/shared/util/validatePetName.ts
Labels: 🎨 design, 🚀api

#191 [Feat/#187] QA2차 적용
  src/page/community/[postId]/PostDetail.tsx
  src/page/community/utills/handleCategoryItem.tsx
  src/type/schema.d.ts
Labels: 🐞 fix, 📦 chore

#193 [Feat/#165] 로티 적용
  package.json
  pnpm-lock.yaml
  src/asset/lottie/loading.json
  src/asset/lottie/onboarding.json
  src/asset/lottie/registerPet.json
  src/common/component/Loading/Loading.css.ts
  src/common/component/Loading/Loading.tsx
  src/page/login/Login.tsx
  src/page/onboarding/complete/Complete.css.ts
  src/page/onboarding/complete/Complete.tsx
  src/page/register-pet/complete/Complete.css.ts
  src/page/register-pet/complete/Complete.tsx
Labels: 🎨 design, ✨ feat

#201 [Fix/#199] 로티 라이브러리 변경
  package.json
  pnpm-lock.yaml
  src/common/component/Loading/Loading.css.ts
  src/common/component/Loading/Loading.tsx
  src/page/onboarding/complete/Complete.tsx
  src/page/register-pet/complete/Complete.tsx
Labels: 🐞 fix, 🎨 design

#198 [feat/#197] QA-3차
  public/svgs/ic_addphoto.svg
  src/asset/svg/IcAddphoto.tsx
  src/asset/svg/index.ts
  src/common/component/Loading/Loading.css.ts
  src/common/component/Loading/Loading.tsx
  src/page/community/[postId]/PostDetail.css.ts
  src/page/community/[postId]/PostDetail.tsx
  src/page/community/category/Category.tsx
  src/page/community/index/components/SelectPost/SelectPost.tsx
  src/page/community/search/done/SearchDone.css.ts
  src/page/community/search/done/SearchDone.tsx
  src/page/community/search/index/Search.tsx
  src/page/community/write/Write.tsx
  src/page/main/index/symptomDetail/SymptomDetail.css.ts
  src/page/mypage/index/component/MyPageContent/MyPageContent.css.ts
  src/page/mypage/index/component/MyPageContent/MyPageContent.tsx
  src/page/onboarding/index/component/nickname/Nickname.tsx
  src/page/profile/index/component/ProfileContent/ProfileContent.css.ts
  src/page/profile/index/component/ProfileContent/ProfileContent.tsx
  src/page/register-pet/index/RegisterPet.tsx
  src/page/register-pet/index/component/petHealth/PetHealth.tsx
Labels: 🎨 design

#214 [design] 프로그래스바 변경
  src/page/register-pet/index/common/ProgressBar/ProgressBar.css.ts
Labels: 🎨 design

#228 [Feat/#225]onboarding qa2 반영
  src/common/component/Button/styles.css.ts
  src/page/register-pet/index/component/petName/PetName.tsx
Labels: 🐞 fix, 🎨 design
