Repository cocos-pet/cocos-frontend, pull requests merged in 2025-05, with the labels that each got.

#270 [Feat/#269] 닉네임 api 변경사항 반영
  src/api/domain/onboarding/hook.ts
  src/api/domain/onboarding/index.ts
  src/api/domain/onboarding/nickname/hook.ts
  src/api/domain/onboarding/nickname/index.ts
Labels: 🚀api

#268 [Feat/#266] 리뷰 등록 완료 뷰 퍼블리싱
  src/app/review/complete/page.tsx
  src/app/review/complete/style.css.ts
Labels: 🎨 design, ✨ feat

#262 [Feat/#261] main home 인기 병원 목록 추가
  .github/workflows/forkMain.yml
  README.md
  src/app/main/Main.css.ts
  src/app/main/_component/HotHospitalItem/HotHospitalItem.css.ts
  src/app/main/_component/HotHospitalItem/HotHospitalItem.tsx
  src/app/main/_section/hotHospital/HotHospital.css.ts
  src/app/main/_section/hotHospital/HotHospital.tsx
  src/app/main/_section/hotPost/HotPost.css.ts
  src/app/main/_section/hotPost/HotPost.tsx
  src/app/main/_section/mainFooter/MainFooter.css.ts
  src/app/main/_section/mainFooter/MainFooter.tsx
  src/app/main/_section/mainHeader/Carousel/Images.ts
  src/app/main/_section/mainHeader/Carousel/mainCarousel.css.ts
  src/app/main/_section/mainHeader/Carousel/mainCarousel.tsx
  src/app/main/_section/mainHeader/mainHeader.css.ts
  src/app/main/_section/mainHeader/mainHeader.tsx
  src/app/main/_section/symptom/Symptom.css.ts
  src/app/main/_section/symptom/Symptom.tsx
  src/app/main/_section/symptomDetail/SymptomDetail.css.ts
  src/app/main/_section/symptomDetail/SymptomDetail.tsx
  src/app/main/index/Main.tsx
  src/app/main/page.tsx
  src/route/MainRoutes.tsx
Labels: 🎨 design, ✨ feat, ♻️ refactor

#295 [Feat/#294] 병원 검색 바텀 시트 API 연결 및 무한 스크롤 구현
  src/api/constants/apiPath.ts
  src/api/shared/hook.ts
  src/api/shared/index.ts
  src/app/mypage/_component/AddFavoriteHospital.tsx
  src/shared/component/SearchHospital/Card.tsx
  src/shared/component/SearchHospital/SearchHospital.css.ts
  src/shared/component/SearchHospital/SearchHospital.tsx
  src/type/schema.d.ts
Labels: 🎨 design, 🚀api

#284 [Feat/#283] fillter bottom sheet
  public/svgs/ic_down_arrow.svg
  public/svgs/ic_target.svg
  src/app/community/_constant/reviewFilterConfig.ts
  src/app/community/_constant/reviewMockData.ts
  src/app/community/detail/SymptomDetail.css.ts
  src/app/community/detail/_section/CommunityDetailContent.tsx
  src/app/community/detail/_section/LoadingFallback.tsx
  src/app/community/detail/_section/ReviewDetailContent.tsx
  src/app/community/detail/_section/ReviewFilter.tsx
  src/app/community/detail/_section/index.tsx
  src/app/community/detail/page.tsx
  src/app/main/_section/hotHospital/HotHospital.tsx
  src/app/main/index/hotPost/HotPost.tsx
  src/app/mypage/edit-pet/_component/AgeBottomSheet/AgeBottomSheet.tsx
  src/app/mypage/edit-pet/_component/AnimalBottomSheet/AnimalBottomSheet.tsx
  src/app/mypage/edit-pet/_component/CategoryBottomSheet/CategoryBottomSheet.tsx
  src/asset/svg/IcDownArrow.tsx
  src/asset/svg/IcTarget.tsx
  src/asset/svg/index.ts
  src/common/component/Button/index.tsx
  src/common/component/Chip/Chip.tsx
  src/common/component/Chip/ChipStyle.css.ts
  src/shared/component/FilterBottomSheet/FilterBottomSheet.tsx
Labels: ✨ feat

#293 [Feat/#292] 리뷰작성 3-4페이지
  src/api/constants/apiPath.ts
  src/app/api/review/write/feedback/hook.ts
  src/app/api/review/write/feedback/index.ts
  src/app/review/write/_component/FeedbackCategoryContent.style.css.ts
  src/app/review/write/_component/FeedbackCategoryContent.tsx
  src/app/review/write/_component/ReviewContent.style.css.ts
  src/app/review/write/_component/ReviewContent.tsx
  src/app/review/write/_component/ReviewImg.styles.css.ts
  src/app/review/write/_component/ReviewImg.tsx
  src/app/review/write/_section/Step1.tsx
  src/app/review/write/_section/Step3.style.css.ts
  src/app/review/write/_section/Step3.tsx
  src/app/review/write/_section/Step4.style.css.ts
  src/app/review/write/_section/Step4.tsx
  src/asset/image/reviewFeedback.png
  src/common/component/ColorChip/ColorChip.style.css.ts
  src/common/component/ColorChip/ColorChip.tsx
  src/common/component/SimpleBottomSheet/SimpleBottomSheet.css.ts
  src/common/component/Tab/Tab.css.ts
  src/common/component/Tab/Tab.tsx
  src/route/path.ts
  src/style/styles.css.ts
Labels: 🎨 design, ✨ feat, 🚀api

#334 [Feat][#333] useProtectedRoute 적용 필요 없는 곳에서 제거
  src/app/community/[postId]/page.tsx
  src/app/community/index/Community.tsx
  src/app/community/write/Write.tsx
  src/app/community/write/page.tsx
  src/app/login/Login.tsx
  src/app/login/page.tsx
  src/app/main/page.tsx
  src/app/mypage/page.tsx
  src/app/profile/page.tsx
  src/app/setting/edit-profile/ProfileEdit.tsx
  src/app/setting/index/Setting.tsx
  src/app/setting/page.tsx
Labels: 🍳 simple review
